export default {
    
    isLogged: undefined,
    isLoggedOut: undefined,
    user_id: "",
    name: "",
    email: "",
    about_me: "",
    profile_img:"",
    phone_number:"",
    city: "",
    country: "",
    company: "",
    school: "",
    hometown: "",
    languages: "",
    gender: "",
    isStudent: "",
    course_list:[],
    courseDetails : {
        allAssignment : [],
        announcement : [],
        peoples: [],
        assignment : [],
        allQuizzes: []
    },
    all_courses:[],
    isFull: "",
    enrollmentCount: "",
    code: "",
    component_details: [],
    all_messages: [],
    all_people: [],
    quiz: [{question: "", answers: []}],
    quiz_details: [],
    quizid_details: [],
    quiz_ans: "",
    assignment_submissions: [],
}
